<?php

namespace CitiesBundle\Repository;

/**
 * AvisRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AvisRepository extends \Doctrine\ORM\EntityRepository
{
    public function deleteAllAvis()
    {
        $sql = "TRUNCATE avis";
        $conn = $this->getEntityManager()->getConnection();

        $query = $conn->query($sql);
        $query->execute();
    }
}
