<?php

namespace CitiesBundle\Repository;

/**
 * DepartementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DepartementRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAll($order)
    {
        return $this->findBy(
            array(),
            array('name' => $order)
        );
    }

    public function getAllBypackage($limit, $offset, $criteres = array(), $order = array())
    {
        return $this->findBy(
            $criteres,
            $order,
            $limit,
            $offset
        );
    }

    public function getCount()
    {
        return count($this->findAll());
    }
}
