<?php

namespace CitiesBundle\Repository;

/**
 * RegionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RegionRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Return region by code
     * @param $code
     * @return mixed
     */
    public function getRegionByCode($code) {
        return $this->getEntityManager()
                    ->findOneBy(array('code'=>$code));
    }

    public function getAll($order)
    {
        return $this->findBy(array(), array('name' => $order));
    }
}
