<?php

namespace CitiesBundle\Repository;

/**
 * StatsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StatsRepository extends \Doctrine\ORM\EntityRepository
{
    public function getEntity($type, $entity_id)
    {
        switch ($type) {
            case 'region':
                $entity = "CitiesBundle:Region";
            break;
            case 'departement':
                $entity = "CitiesBundle:Departement";
            break;
            case 'ville':
                $entity = "CitiesBundle:Ville";
            break;
            default:
                throw new \Exception("Le type d'entité est inconnu ".$type.", il doit être region, departement ou ville");
            break;
        }
        $repository = $this->getEntityManager()->getRepository($entity);
        return $repository->find($entity_id);
    }
}
