services:
#    cities.example:
#        class: CitiesBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    cities.region:
        class: CitiesBundle\Services\Region
        arguments:
            - "@doctrine.orm.entity_manager"
    cities.departement:
        class: CitiesBundle\Services\Departement
        arguments:
            - "@doctrine.orm.entity_manager"
    cities.ville:
        class: CitiesBundle\Services\Ville
        arguments:
            - "@doctrine.orm.entity_manager"
    cities.stats:
        class: CitiesBundle\Services\Stats
        arguments:
            - "@doctrine.orm.entity_manager"
    cities_pagination:
        class: CitiesBundle\Services\Pagination
    cities.general.csv:
        class: CitiesBundle\Services\Csv
    cities.general.xml:
        class: CitiesBundle\Services\XmlParser
        arguments:
            - "@doctrine.orm.entity_manager"
    cities.general.jsencode:
        class: CitiesBundle\Services\JsEncode
    cities.handle.avis:
        class: CitiesBundle\Services\ServiceHandleAvis
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@service_container"

