services:
#    cities.example:
#        class: CitiesBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    cities.region:
        class: CitiesBundle\Services\Region
        arguments:
            - "@doctrine.orm.entity_manager"
    cities.departement:
            class: CitiesBundle\Services\Departement
            arguments:
                - "@doctrine.orm.entity_manager"
    cities.ville:
            class: CitiesBundle\Services\Ville
            arguments:
                - "@doctrine.orm.entity_manager"
    cities_pagination:
            class: CitiesBundle\Services\Pagination
